### ISSUE TITLE
demo doesn't work with pip install

### ISSUE THREAD

**Issue by lionfish0** [pmorenoz/HetMOGP#3]
I installed the module successfully with
`pip install git+https://github.com/pmorenoz/HetMOGP.git`
but when I tried to use the `demo.ipynb` it didn't work. This is because it includes imports of the `likelihoods` folder which isn't installed with pip.

**Comment by pmorenoz** [comment]
the "likelihoods" folder was not included in the setup.py. Now it is. Thanks for pointing this out!
